In [1]:
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier

In [2]:
synth_df = pd.read_csv('./synthetic_knn.csv')
synth_df.head()

id   X   Y  Class
0   1  56  82      1
1   2  96  36      0
2   3  78  73      1
3   4  69  19      1
4   5  12  44      1

In [23]:
Xs = synth_df['X']
Ys = synth_df['Y']
X = []

for i in range(len(Xs)):
    X.append((Xs[i], Ys[i]))
    
X = np.array(X)
Y = np.array(synth_df['Class'])

In [24]:
point = np.array([(17, 94)])

neigh = KNeighborsClassifier(n_neighbors=1, metric='euclidean').fit(X, Y)
neigh.kneighbors(X=point, n_neighbors=3)

(array([[11.18033989, 29.42787794, 40.80441153]]), array([[9, 8, 0]]))

In [30]:
neigh = KNeighborsClassifier(n_neighbors=3, metric='euclidean').fit(X, Y)
neigh.predict(point)

array([1])

In [26]:
neigh = KNeighborsClassifier(n_neighbors=1, metric='manhattan').fit(X, Y)
neigh.kneighbors(X=point)

(array([[13.]]), array([[9]]))

In [27]:
neigh.kneighbors(X=point, n_neighbors=3)

(array([[13., 34., 51.]]), array([[9, 8, 0]]))

In [29]:
neigh = KNeighborsClassifier(n_neighbors=3, metric='manhattan').fit(X, Y)
neigh.predict(point)

array([1])